### ISSUE TITLE
Line 922: Special Processing for fieldmaps to make them BIDS compatible (GE)

### ISSUE THREAD

**Issue by tbweng** [HBClab/GE_dcm_to_nii#1]
When reconstructing with -r flag, cannot find this file (line 925): $outDir/${outBase}${imageExt} because this chunk of code follows RPI reorientation and renaming. Suggest changing to (if -r flag): $outDir/${outBase}_RPI${imageExt}

**Comment by jdkent** [comment]
Thanks for the bug find! I think I fixed it with your suggestion, but it should be tested. [Here's the commit](https://github.com/HBClab/GE_dcm_to_nii/commit/daa29395a2d56c6007375f57962c4478e0f32fda#diff-dc8a9f6f353169bf341bbc778acb55e9)

**Comment by jdkent** [comment]
closing this issue, let me know if it's still an issue
